Update zh-cn/srs/thailand/preecha.md
mtf-wiki/MtF-Wiki pull request #1004
Opened 2024-04-07 15:20 UTC by Dolyn157

在简中 PAI 的页面增加了“术前请与医师沟通具体的手术方案”的提醒。

2024-04-10 12:35 UTC, clansty requested changes

2024-04-10 12:35 UTC, clansty commented on content/zh-cn/docs/srs/thailand/preecha.md
> +术前请和医师充分沟通手术方案说明自己的需求，例如不希望深度超过 x 厘米。目前收到过姐妹术前提出希望零深度但术后发现阴道深度达到近 10 厘米，医师建议她术后护理需要通最小号模具的案例。
```suggestion

术前请和医师充分沟通手术方案说明自己的需求，例如不希望深度超过 x 厘米。目前收到过姐妹术前提出希望零深度但术后发现阴道深度达到近 10 厘米，医师建议她术后护理需要通最小号模具的案例。
```

markdown 里面新的段落需要空一行，或者在前一行加两个空格来增加一个没有间距的“硬换行”（不建议）

2024-04-11 09:14 UTC, Dolyn157 reviewed
Ok, got it.

2024-04-11 11:56 UTC, clansty approved these changes

2024-04-11 11:56 UTC, LittleSound approved these changes
LGTM

2024-04-11 12:56 UTC, Cryolitia approved these changes

2024-04-11 12:56 UTC, merged