PAI | 更新脱毛相关信息
mtf-wiki/MtF-Wiki pull request #1011
Opened 2024-04-16 06:07 UTC by AnnaBeiyan

信息来源：https://pai.co.th/service/penile-skin-inversion-scrotal-skin-graft-male-to-female-trans-women/

> Q: What is the average wait-list for penile inversion or other method at PAI?
> A: Schedule/planning at least 1 month ahead of time.
>
> Q: Is genital hair removal mandatory for penile inversion?
> A: No. (this is not necessary but just an option). For your sake, even thru, the surgeon will also scrape the root of hair from penile and scrotal skin during surgical times (hair follicle scraping). 

relate #617

2024-04-16 06:44 UTC, LittleSound commented on content/zh-cn/docs/srs/thailand/preecha.md
> +1. 医生会在手术时刮掉部分区域皮肤的发根，以避免术后阴道内生长毛发。因此手术前进行生殖器位置脱毛不是必须的。
与我了解的情况类似，另外医生说构造阴道内部使用到的那部分皮肤一般情况下就不会有什么毛。

2024-04-16 06:51 UTC, AnnaBeiyan commented on content/zh-cn/docs/srs/thailand/preecha.md
> +1. 医生会在手术时刮掉部分区域皮肤的发根，以避免术后阴道内生长毛发。因此手术前进行生殖器位置脱毛不是必须的。
那这部分需要修改吗？

2024-04-16 09:10 UTC, LittleSound commented on content/zh-cn/docs/srs/thailand/preecha.md
> +1. 医生会在手术时刮掉部分区域皮肤的发根，以避免术后阴道内生长毛发。因此手术前进行生殖器位置脱毛不是必须的。
这不是修改建议，你可以自己决定。

2024-04-18 06:02 UTC, Cryolitia requested changes

2024-04-18 06:02 UTC, Cryolitia commented on content/zh-cn/docs/srs/thailand/preecha.md
> +1. 医生会在手术时刮掉部分区域皮肤的发根，以避免术后阴道内生长毛发。因此手术前进行生殖器位置脱毛不是必须的。
这里加个引用来源

2024-04-18 06:03 UTC, Cryolitia commented
另外繁体中文我建议直接删，不要机翻，没有维护者就让他们看简体好了，CC @project-trans/chairs

2024-04-18 08:37 UTC, AnnaBeiyan commented on content/zh-cn/docs/srs/thailand/preecha.md
> +1. 医生会在手术时刮掉部分区域皮肤的发根，以避免术后阴道内生长毛发。因此手术前进行生殖器位置脱毛不是必须的。
加了

2024-04-19 02:43 UTC, Cryolitia approved these changes

2024-04-19 02:54 UTC, BeiyanYunyi approved these changes

2024-04-19 03:19 UTC, LittleSound approved these changes

2024-04-19 03:35 UTC, merged