优化并上传mtf-wiki-square.svg和favicon.png
mtf-wiki/MtF-Wiki pull request #1180
Opened 2024-10-24 05:39 UTC by ChisakaKanako

2024-10-24 05:58 UTC, Leetfs commented
辛苦留意下logo精度问题，以及导航栏和主页的logo样式。


![Screenshot_2024-10-24-13-56-27-859_com.android.chrome-edit.jpg](https://github.com/user-attachments/assets/24ed6fff-4300-4d81-b6b3-83f004b8e8af)

![Screenshot_2024-10-24-13-55-09-836_com.android.chrome-edit.jpg](https://github.com/user-attachments/assets/12909b4b-670d-45b4-b18a-a0d76e5a3fc7)

2024-10-24 06:30 UTC, ChisakaKanako commented
已修复

2024-10-24 06:43 UTC, Leetfs requested changes
移动设备视图的图片大小异常，放着别动，等我回去改一下。

2024-10-24 07:05 UTC, Leetfs commented on static/new/mtf-wiki-square.svg
> +<!-- Created with Inkscape (http://www.inkscape.org/) -->
```suggestion
<svg width="267px" height="244px" viewBox="0 0 267 244" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
```

2024-10-24 07:17 UTC, Leetfs reviewed
~~手机上改的，将就看吧~~

2024-10-24 07:17 UTC, Leetfs commented on static/new/mtf-wiki-square.svg
>  <svg width="267px" height="244px" viewBox="0 0 267 244" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
```suggestion
```

2024-10-24 07:17 UTC, Leetfs commented on static/new/mtf-wiki-square.svg
> +   width="356"
```suggestion
   width="267"
```

2024-10-24 07:17 UTC, Leetfs commented on static/new/mtf-wiki-square.svg
> +   height="325.33334"
```suggestion
   height="244"
```

2024-10-24 07:17 UTC, Leetfs commented on static/new/mtf-wiki-square.svg
> +   viewBox="0 0 356 325.33334"
```suggestion
   viewBox="0 0 267 244"
```

2024-10-24 07:36 UTC, Leetfs approved these changes

2024-10-26 09:43 UTC, Cryolitia approved these changes

2024-10-26 09:43 UTC, merged