微小的贡献
mtf-wiki/MtF-Wiki pull request #265
Opened 2022-01-25 19:12 UTC by RealYingxi

2022-01-25 20:26 UTC, septs commented on content/zh-cn/docs/psyco/southwest/li-hui/index.md
> +{{< notice info >}} 李阿姨下乡了！大概4月回来。期间可以找同院周波开证，情况基本相同。 {{< /notice >}}
不接受时效性较短的内容

2022-01-26 06:11 UTC, Rinfair-CSP-A016 requested changes

2022-01-26 06:11 UTC, Rinfair-CSP-A016 commented on content/zh-cn/docs/psyco/southwest/li-hui/index.md
> +{{< notice info >}} 李阿姨下乡了！大概4月回来。期间可以找同院周波开证，情况基本相同。 {{< /notice >}}
此信息时效性较短，请不要加入。

2022-01-26 08:41 UTC, Rinfair-CSP-A016 requested changes
请注意不要更改原文件路径！！！

2022-01-26 12:53 UTC, RealYingxi commented
> 请不要更改原文件路径！！！

修改完成 之前想用手机chrome改改 结果被自动翻译坑了（

2022-01-26 13:37 UTC, Rinfair-CSP-A016 approved these changes

2022-01-26 13:41 UTC, merged