Update information about Peking University Third Hospital
mtf-wiki/MtF-Wiki pull request #304
Opened 2022-02-07 14:02 UTC by ArtsEpiphany

2022-02-07 14:05 UTC, ArtsEpiphany commented on content/zh-cn/docs/hrt/puth/_index.md
> +collapsible: true
我没动这里

2022-02-07 14:06 UTC, ArtsEpiphany commented on content/zh-cn/docs/hrt/puth/_index.md
> +-	北京大学第三医院（主院区）：位于[北京市海淀区花园北路 49 号](https://amap.com/place/B000A7CGSS)，潘柏林、刘烨等医生通常在此出诊。最近的地铁站为地铁 10 号线西土城站。
那是换行符

2022-02-07 14:06 UTC, ArtsEpiphany commented on content/zh-cn/docs/hrt/puth/_index.md
> +-	北京大学第三医院（主院区）：位于[北京市海淀区花园北路 49 号](https://amap.com/place/B000A7CGSS)，潘柏林、刘烨等医生通常在此出诊。最近的地铁站为地铁 10 号线西土城站。
呜呜我要把他们改成空格吗

2022-02-07 14:41 UTC, septs commented on content/zh-cn/docs/hrt/puth/liu-ye/index.md
> +    - /zh-cn/docs/hrt/pku3/liu-ye/
```suggestion
    - ../pku3/liu-ye
```

2022-02-07 14:41 UTC, septs commented on content/zh-cn/docs/hrt/puth/pan-bailin/index.md
> +    - /zh-cn/docs/hrt/pku3/pan-bailin/
```suggestion
    - ../pku3/pan-bailin
```

2022-02-07 14:42 UTC, ArtsEpiphany commented on content/zh-cn/docs/hrt/puth/liu-ye/index.md
> +    - /zh-cn/docs/hrt/pku3/liu-ye/
我不赞成，因为文件结构可能再次被改动

2022-02-07 14:44 UTC, septs commented on content/zh-cn/docs/hrt/puth/_index.md
> +- 北方院区：位于[北京市海淀区车道沟 10 号](https://amap.com/place/B0GRM70KV2)。最近的地铁站为地铁 10 号线车道沟站。
这些信息属于干扰信息无需列出

2022-02-07 14:44 UTC, ArtsEpiphany commented on content/zh-cn/docs/hrt/puth/liu-ye/index.md
> +    - /zh-cn/docs/hrt/pku3/liu-ye/
绝对路径反而更安全

2022-02-07 15:31 UTC, Rinfair-CSP-A016 commented on content/zh-cn/docs/hrt/puth/_index.md
> +- 北方院区：位于[北京市海淀区车道沟 10 号](https://amap.com/place/B0GRM70KV2)。最近的地铁站为地铁 10 号线车道沟站。
仅列举所有进行HRT前、中间需要抵达的院区即可

2022-02-07 15:54 UTC, ArtsEpiphany commented on content/zh-cn/docs/hrt/puth/liu-ye/index.md
> +    - /zh-cn/docs/hrt/pku3/liu-ye/
> 考虑到文件结构可能被改动的情况，使用..替代前置路径更保险

不是的，再想想？（笑眯眯

2022-02-08 14:40 UTC, septs commented on content/zh-cn/docs/hrt/puth/_index.md
> +总花费在 1000 到 2000 元之间。
```suggestion
总花费介于 1k - 2k 之间。
```

2022-02-08 14:40 UTC, septs commented on content/zh-cn/docs/hrt/puth/_index.md
> +骨密度与乳腺超声是开具处方的必要条件，如因个人原因导致无法在预约时间前往，可拨打分诊台电话 010-82264567 申请更改时间。
```suggestion
骨密度与乳腺超声是开具处方的必要条件，如因个人原因导致无法在预约时间前往，可拨打分诊台电话 {{< telephone "+86 010-8226-4567" >}} 申请更改时间。
```

2022-02-08 14:41 UTC, septs commented on content/zh-cn/docs/hrt/puth/_index.md
> +- 杨文慧 _成型科_
请使用表格形式表示

```
{{< csv-table >}}
医师,门诊
.....
{{</ csv-table >}}
```

2022-02-08 14:42 UTC, septs commented on content/zh-cn/docs/hrt/puth/_index.md
> + 120 元。
```suggestion
目前，北医三院跨性别医疗团队支持通过好大夫在线平台进行在线问诊，方式同时支持图文问诊与简短咨询方式，为方便流畅的沟通和检查相关资料得发送，建议使用图文问诊方式，好大夫在线平台图文问诊得价格目前为 120 元。
```

2022-02-08 15:06 UTC, Rinfair-CSP-A016 requested changes
请确保格式一致

2022-02-08 15:06 UTC, Rinfair-CSP-A016 commented on content/zh-cn/docs/psyco/beijing/cong-zhong/index.md
>  {{< alert theme=danger >}}可用于手术的正式证明需两年观察期，凭介绍信开具。须没有严重精神问题。{{< /alert >}}
```suggestion
{{< alert theme="danger" >}}
可用于手术的正式证明需两年观察期，凭介绍信开具。须没有严重精神问题。
{{< /alert >}}
```

2022-02-08 15:10 UTC, Rinfair-CSP-A016 approved these changes

2022-02-08 15:17 UTC, saeziae approved these changes

2022-02-08 15:17 UTC, merged