update care
mtf-wiki/MtF-Wiki pull request #391
Opened 2022-03-02 17:55 UTC by diankao

写了114514点东西

2022-03-02 18:55 UTC, diankao commented
> 写了114514点垃圾

2022-03-03 06:38 UTC, saeziae requested changes
preecha 即現有頁面 burin，請併入 burin 頁面。
順祝文琪

2022-03-03 08:16 UTC, saeziae commented on content/zh-cn/docs/srs/care.md
> +在术者仍然频繁扩张的初期，应每天冲洗阴道。扩张频率降低后，冲洗可以减少到每周 2~3 次。阴道的异味或分泌物有些是冲洗可以解决的，有些则不是，请参考后文[阴道分泌物](#阴道分泌物)栏目。
沖洗陰道這個要求似乎並不common，此處是否指沖洗外陰/陰道口

2022-03-03 08:21 UTC, diankao commented on content/zh-cn/docs/srs/care.md
> +在术者仍然频繁扩张的初期，应每天冲洗阴道。扩张频率降低后，冲洗可以减少到每周 2~3 次。阴道的异味或分泌物有些是冲洗可以解决的，有些则不是，请参考后文[阴道分泌物](#阴道分泌物)栏目。
未知，由于本文撰写于半年前已经遗忘了引用来源

2022-03-03 09:00 UTC, saeziae approved these changes

2022-03-03 09:18 UTC, llh721113 approved these changes

2022-03-03 10:10 UTC, septs commented on content/zh-cn/docs/ffs/hair-loss-med.md
> +title:hair-loss-medical-treatment
```suggestion
title: hair-loss-medical-treatment
```

2022-03-03 10:27 UTC, saeziae commented on content/zh-cn/docs/ffs/hair-loss-med.md
> +# 概述
增加一级`#`，从h2开始

2022-03-04 17:10 UTC, ArtsEpiphany reviewed
我只看了一下格式上的情况，内容方面鸭鸭肯定比我了解得多啦～

2022-03-04 17:10 UTC, ArtsEpiphany commented on content/zh-cn/docs/srs/thailand/thailand-tips.md
> +  {{< /expand >}}
为什么要这样修改呢

2022-03-04 17:10 UTC, ArtsEpiphany commented on content/zh-cn/docs/vocal-surgery/vocal-surgery-overview.md
> +## 影响嗓音的因素[^1]
再次提醒，请注意渲染效果

2022-03-04 17:10 UTC, ArtsEpiphany commented on content/zh-cn/docs/vocal-surgery/vocal-surgery-overview.md
> +2. HRT 一年以上，有三级以上医院精神心理门诊易性症/性别不安诊断证明；
建议统一格式，有/无结尾分号

2022-03-05 03:29 UTC, diankao commented on content/zh-cn/docs/srs/thailand/thailand-tips.md
> +  {{< /expand >}}
手癌（（

2022-03-05 03:34 UTC, diankao commented on content/zh-cn/docs/ffs/ffs-overview.md
> +## 常见面部女性化手术项目[^1]
确认

2022-03-05 11:57 UTC, merged