增加了关于SERMs的说明
mtf-wiki/MtF-Wiki pull request #433
Opened 2022-03-27 08:04 UTC by zx013

调整了格式，分成了SERMs介绍和雷洛昔芬的药物说明，并给出了一个HRT方案（目前我正在尝试的方案，其他方案暂时没有放上来，因为效果还不太明确）

2022-03-27 10:24 UTC, Clansty reviewed
我觉得 `SERMs.md` 的内容应该是放在 `SERMs/_index.md` 中吧，不然侧边栏怕不是会有两个选项

2022-03-27 10:27 UTC, Clansty requested changes

2022-03-27 10:27 UTC, Clansty commented on content/zh-cn/docs/medicine/SERMs/raloxifen/index.md
> +![beibang](beibang.jpg)
```suggestion
![贝邦 盐酸雷洛昔芬片包装](beibang.jpg)
```

2022-03-28 04:29 UTC, ArtsEpiphany reviewed
感谢调整！请注意雷洛昔芬的英文名称可能是Raloxifene，如果你也认可这一点，请修改目录raloxifen为raloxifene。

2022-03-28 04:29 UTC, ArtsEpiphany commented on content/zh-cn/docs/medicine/SERMs.md
> +> **选择性雌激素受体调节剂（selective estrogen receptormodulators，SERMs）** 是一类作用于雌激素受体（ER）的药物。SERMs在不同组织中起到ER激动剂和拮抗剂的作用。SERMs在各种组织中的作用不同，从而提供了选择性地在不同组织中起到类似雌激素的作用。
即使你决定用小写，这里也少了个空格
```suggestion
> **选择性雌激素受体调节剂（Selective Estrogen Receptor Modulators，SERMs）** 是一类作用于雌激素受体（ER）的药物。SERMs在不同组织中起到ER激动剂和拮抗剂的作用。SERMs在各种组织中的作用不同，从而提供了选择性地在不同组织中起到类似雌激素的作用。
```

2022-03-28 04:29 UTC, ArtsEpiphany commented on content/zh-cn/docs/medicine/SERMs/raloxifen/index.md
> +description: 雷洛昔芬（raloxifen），是一种常见的SERMs，在跨性别人群中主要用于抑制胸部发育。
据我所知雷洛昔芬的英文名称为Raloxifene
```suggestion
description: 雷洛昔芬（Raloxifene），是一种常见的SERMs，在跨性别人群中主要用于抑制胸部发育。
```

2022-03-29 12:04 UTC, ArtsEpiphany commented on content/zh-cn/docs/medicine/SERMs/_index.md
> +[^2]: [雷洛昔芬](https://m.chemicalbook.com/ProductChemicalPropertiesCB1290431.htm)
之前的链接指向了移动版页面，在电脑上打开会不利于阅读。如果这样修改的话，在电脑上可以正常显示，在移动设备上也会自动跳转至移动版页面
```suggestion
[^2]: [雷洛昔芬](https://www.chemicalbook.com/ProductChemicalPropertiesCB1290431.htm)
```

2022-03-29 12:24 UTC, merged