Update SSPU.md
mtf-wiki/MtF-Wiki pull request #475
Opened 2022-05-24 14:01 UTC by thelovelymomogirl

进行第二次修订，并添加了在校期间的学籍信息修改流程

2022-05-26 02:46 UTC, ArtsEpiphany reviewed
感谢提交pr！其实这个页面之前就已经很详尽了，没想到你会再次来完善内容。可以看出你努力地借鉴了其他页面的设计，使wiki协调一致。辛苦你了，正是与你一样的人们的无私奉献，使得wiki日臻完善。

变更内容有点多，我简单地试着改了一下格式，一些内容上的可能的不足之处我没有来得及修正。或许将来有机会，我们可以重新设计一下页面呢。

2022-05-26 02:46 UTC, ArtsEpiphany commented on content/zh-cn/docs/campus/china/SSPU.md
> +上海第二工业大学成立于1960年，是一所工科见长，管经文理艺多学科协调发展，以本科教育为主体，同时拥有专业学位研究生教育和国际化高职教育的市属普通高等学校。学校地处上海浦东金桥地区，紧邻上海自由贸易试验区，与众多世界500强企业毗邻，具有天然的产教融合和国际交流的区域优势。
```suggestion
[上海第二工业大学](https://www.sspu.edu.cn)（Shanghai Polytechnic University，sspu）成立于 1960 年，是一所工科见长，管经文理艺多学科协调发展，以本科教育为主体，同时拥有专业学位研究生教育和国际化高职教育的市属普通高等学校。学校地处上海浦东金桥地区，紧邻上海自由贸易试验区，与众多世界 500 强企业毗邻，具有天然的产教融合和国际交流的区域优势。
```

2022-05-26 02:46 UTC, ArtsEpiphany commented on content/zh-cn/docs/campus/china/SSPU.md
> +#### 宿舍
“宿舍”和“宿舍的分配”等等并列不太合适，建议如此修改，讲此段作为概述
```suggestion
```

2022-05-26 02:46 UTC, ArtsEpiphany commented on content/zh-cn/docs/campus/china/SSPU.md
> +住宿费全员都是三、四人间1200软妹币/年，六人间1050软妹币/年
```suggestion
住宿费全员都是三、四人间 1200 软妹币/年，六人间 1050 软妹币/年
```

2022-05-26 02:46 UTC, ArtsEpiphany commented on content/zh-cn/docs/campus/china/SSPU.md
> +- 今年学校比往年提前了一个月放暑假，我们也比往年提前了一个月毕业，为了有充足的时间翻新宿舍。但是今年上海疫情严重，这个施工进度不知道会不会受到影响，开学前翻新好的宿舍也不知道能不能准备就绪，大家敬请期待
```suggestion
- 今年（2022年）学校比往年提前了一个月放暑假，我们也比往年提前了一个月毕业，为了有充足的时间翻新宿舍。但是今年上海疫情严重，这个施工进度不知道会不会受到影响，开学前翻新好的宿舍也不知道能不能准备就绪，大家敬请期待
```

2022-05-26 02:46 UTC, ArtsEpiphany commented on content/zh-cn/docs/campus/china/SSPU.md
> +暂时没有专门的研究生宿舍；关于研究生的住宿，招生简章上的描述是「向有住宿需求的研究生提供宿舍，住宿费不超过1200软妹币/年」，说明如果读研期间要住宿的话，条件应该还是和本专科生差不多。金海路校区扩展工程和三期工程正在建设中，也许会有专门的研究生宿舍，敬请期待
```suggestion
暂时没有专门的研究生宿舍；关于研究生的住宿，招生简章上的描述是「向有住宿需求的研究生提供宿舍，住宿费不超过 1200 软妹币/年」，说明如果读研期间要住宿的话，条件应该还是和本专科生差不多。金海路校区扩展工程和三期工程正在建设中，也许会有专门的研究生宿舍，敬请期待
```

2022-05-26 02:46 UTC, ArtsEpiphany commented on content/zh-cn/docs/campus/china/SSPU.md
> +从2020级开始的军训都由本校退伍大学生带，所以应该会很水。
```suggestion
从 2020 级开始的军训都由本校退伍大学生带，所以应该会很水。
```

2022-05-26 02:46 UTC, ArtsEpiphany commented on content/zh-cn/docs/campus/china/SSPU.md
> +军训纳入培养计划，0.5 学分，叫「军事技能」。一般大一军训（9月中下旬开始，时长两周左右），2020级、2021级因疫情改到了大二军训，2022级及以后还不清楚（根据现在学校的安排，2022级可能还是大二军训）。
```suggestion
军训纳入培养计划，0.5 学分，叫「军事技能」。一般大一军训（9 月中下旬开始，时长两周左右），2020 级、2021 级因疫情改到了大二军训，2022 级及以后还不清楚。（根据现在学校的安排，2022 级可能还是大二军训。）
```

2022-05-26 02:46 UTC, ArtsEpiphany commented on content/zh-cn/docs/campus/china/SSPU.md
> +大二军训的话，8月底左右就要返校军训了，可能会很热很热，如果遇到下雨训练就会取消。
```suggestion
大二军训的话，8 月底左右就要返校军训了，可能会很热很热，如果遇到下雨训练就会取消。
```

2022-05-26 02:46 UTC, ArtsEpiphany commented on content/zh-cn/docs/campus/china/SSPU.md
> +  - 晨跑（住宿学生）时间为早上6:50-7:10，在每学期大概第5周-第13周进行。大一和大三重修的在周三和周五跑，大二和大四重修的在周二和周四跑，**不在规定时间跑无效**。有体育馆广场、河南宿舍区、小高层三个起点打卡点，跑到学校北门终点打卡，全程1.2km左右，**一定要在10分钟内跑/走完**，不然就白跑了。有效晨跑次数10次合格，14次满分，没跑满10次的话这门体育课就**挂了**。
```suggestion
  - 晨跑（住宿学生）时间为早上 6:50-7:10，在每学期大概第 5 周-第 13 周进行。大一和大三重修的在周三和周五跑，大二和大四重修的在周二和周四跑，**不在规定时间跑无效**。有体育馆广场、河南宿舍区、小高层三个起点打卡点，跑到学校北门终点打卡，全程 1.2km 左右，**一定要在 10 分钟内跑/走完**，不然就白跑了。有效晨跑次数 10 次合格，14 次满分，没跑满 10 次的话这门体育课就**挂了**。
```

2022-05-26 02:46 UTC, ArtsEpiphany commented on content/zh-cn/docs/campus/china/SSPU.md
> +  - 课外活动（非住宿学生）每学期进行时间和晨跑一致，只是大概在傍晚之前。就是到小高层旁边那个铁丝网围起来的场地里转一圈并打卡，14次满分。
```suggestion
  - 课外活动（非住宿学生）每学期进行时间和晨跑一致，只是大概在傍晚之前。就是到小高层旁边那个铁丝网围起来的场地里转一圈并打卡，14 次满分。
```

2022-05-26 02:46 UTC, ArtsEpiphany commented on content/zh-cn/docs/campus/china/SSPU.md
> +日语专业的老师对跨性别比较友好，我连续参加过两年的日语才艺比赛对此深有体会。日语专业也有xyn，在去年的日语专业招生宣传片中出现了好几次；而且，妳甚至可以享受女孩子的浴衣
```suggestion
日语专业的老师对跨性别比较友好，我连续参加过两年的日语才艺比赛对此深有体会。日语专业也有 xyn，在去年的日语专业招生宣传片中出现了好几次；而且，妳甚至可以享受女孩子的浴衣
```

2022-05-26 02:46 UTC, ArtsEpiphany commented on content/zh-cn/docs/campus/china/SSPU.md
> +药娘裙也有，裙号 787442332 ~ 加裙请备注是本校xyn，来自 MtF Wiki
```suggestion
药娘裙也有，裙号 787442332 ~ 加裙请备注是本校 xyn，来自 MtF Wiki
```

2022-05-26 02:46 UTC, ArtsEpiphany commented on content/zh-cn/docs/campus/china/SSPU.md
> +2114年5月14日
```suggestion
2114 年 5 月 14 日
```

2022-05-26 02:46 UTC, ArtsEpiphany commented on content/zh-cn/docs/campus/china/SSPU.md
> +1. [第二课堂学分](https://mp.weixin.qq.com/s?__biz=MjM5ODgyNDQzMw==&mid=2652628184&idx=1&sn=b1f67890cca65163f8ae8b3f1a271bcc&chksm=bd2b94468a5c1d509ed7fd89d0b374fa4885f415c2dc2bd206a7f54b07ecb2459dd002e6a8
```suggestion
1. [第二课堂学分](https://mp.weixin.qq.com/s?__biz=MjM5ODgyNDQzMw==&mid=2652628184&idx=1&sn=b1f67890cca65163f8ae8b3f1a271bcc)一定要修满
```

2022-05-26 02:46 UTC, ArtsEpiphany commented on content/zh-cn/docs/campus/china/SSPU.md
>  学校主校区位于上海市浦东新区金海路 2360 号，和附近的上海杉达学院、上海立信会计金融学院合称「浦东三校」。有曹路大学城的说法，但是好像只是民间称呼
借机完善一下qwq
```suggestion
学校主校区位于[上海市浦东新区金海路 2360 号](https://amap.com/place/B00155R06J)，和附近的上海杉达学院、上海立信会计金融学院合称「浦东三校」。有曹路大学城的说法，但是好像只是民间称呼
```

2022-05-26 11:24 UTC, septs commented on content/zh-cn/docs/campus/china/SSPU.md
> +{{< /csv-table >}}
```suggestion
```csv
项目,情况
宿舍独卫,✅
宿舍独浴,除小高层部分✅
第三卫生间,❌
校医院服务,❓
军训协商减免,❓
军训凭医疗材料减免,❓
军训不管头发,✅
体育协商减免,❓
体育凭医疗材料减免,❓
医保使用,✅
```
```

2022-05-27 06:08 UTC, septs commented on content/zh-cn/docs/campus/china/SSPU.md
> +在正式毕业前的各照片比对过程中，如果毕业证照片和录取照片、身份证照片差别较大的话，可能会被学信网和上海市学生事务中心反馈显示“身份核验不确定”，并要求提供一张近期的证件照和身份证照片+身份证上的照片供学校复核。[参考解决方案戳这里](http://8.219.61.56/archives/722)
贵站是否提供域名访问？

2022-05-27 07:12 UTC, thelovelymomogirl commented on content/zh-cn/docs/campus/china/SSPU.md
> +在正式毕业前的各照片比对过程中，如果毕业证照片和录取照片、身份证照片差别较大的话，可能会被学信网和上海市学生事务中心反馈显示“身份核验不确定”，并要求提供一张近期的证件照和身份证照片+身份证上的照片供学校复核。[参考解决方案戳这里](http://8.219.61.56/archives/722)
域名暂时没有呢，个人网站还在筹备中

2022-05-27 08:52 UTC, septs commented on content/zh-cn/docs/campus/china/SSPU.md
> +在正式毕业前的各照片比对过程中，如果毕业证照片和录取照片、身份证照片差别较大的话，可能会被学信网和上海市学生事务中心反馈显示“身份核验不确定”，并要求提供一张近期的证件照和身份证照片+身份证上的照片供学校复核。[参考解决方案戳这里](http://8.219.61.56/archives/722)
考虑到该 URL 的稳定性，我认为不适合记载于 MtF.wiki

2022-05-27 10:09 UTC, thelovelymomogirl commented on content/zh-cn/docs/campus/china/SSPU.md
> +在正式毕业前的各照片比对过程中，如果毕业证照片和录取照片、身份证照片差别较大的话，可能会被学信网和上海市学生事务中心反馈显示“身份核验不确定”，并要求提供一张近期的证件照和身份证照片+身份证上的照片供学校复核。[参考解决方案戳这里](http://8.219.61.56/archives/722)
那等我筹备完再把 URL 放上去吧

2022-05-28 01:37 UTC, ArtsEpiphany requested changes
修复错误

2022-05-28 01:37 UTC, ArtsEpiphany commented on content/zh-cn/docs/campus/china/SSPU.md
> +
````suggestion
```

````

2022-05-28 01:45 UTC, ArtsEpiphany commented on content/zh-cn/docs/campus/china/SSPU.md
> +兹有我校 18 ○○ A1 班学生沫馨小姐姐(学号：20181145141)，因更正出生登记性别，学籍姓名由 XXX 更改为沫馨小姐姐，学籍身份证号由 114514191981000010 更改为 1145141919810020 。
```suggestion
兹有我校 18 ○○ A1 班学生沫馨小姐姐（学号：20181145141），因更正出生登记性别，学籍姓名由 XXX 更改为沫馨小姐姐，学籍身份证号由 114514191981000010 更改为 1145141919810020 。
```

2022-05-28 01:47 UTC, ArtsEpiphany approved these changes
辛苦了qwq

2022-05-28 01:47 UTC, ArtsEpiphany commented on content/zh-cn/docs/campus/china/SSPU.md
> +兹有我校 18 ○○ A1 班学生沫馨小姐姐(学号：20181145141)，因更正出生登记性别，学籍姓名由 XXX 更改为沫馨小姐姐，学籍身份证号由 114514191981000010 更改为 1145141919810020 。
```suggestion
兹有我校 18 ○○ A1 班学生沫馨小姐姐（学号：20181145141），因更正出生登记性别，学籍姓名由 XXX 更改为沫馨小姐姐，学籍身份证号由 114514191981000010 更改为 1145141919810020。
```

2022-05-29 12:02 UTC, merged

2022-07-09 14:51 UTC, thelovelymomogirl commented on content/zh-cn/docs/campus/china/SSPU.md
> +在正式毕业前的各照片比对过程中，如果毕业证照片和录取照片、身份证照片差别较大的话，可能会被学信网和上海市学生事务中心反馈显示“身份核验不确定”，并要求提供一张近期的证件照和身份证照片+身份证上的照片供学校复核。[参考解决方案戳这里](http://8.219.61.56/archives/722)
http://moxingirl.cyou/archives/722