更新 精神科/心理科-贺莹医生 相关内容
mtf-wiki/MtF-Wiki pull request #523
Opened 2022-07-02 13:42 UTC by Fe3O4-Git

第一次创建pr，如有错误请指出，咱会改的w

或许可以创建一个 贡献者指南 来对pr稍微做一下规范(?)

2022-07-02 14:19 UTC, Fe3O4-Git commented
病历部分(包括手写和电子病历)似乎对个人情况描述过于详细，是否应该删去？

2022-07-03 03:22 UTC, septs commented on content/zh-cn/docs/psyco/midsouth/he-ying/index.md
> +证明需要三日内去旁边的第一门诊大楼二楼走廊末尾203号办公室盖章生效，可询问导诊台工作人员。
```suggestion
证明需要 3 日内去旁边的 第一门诊大楼 二楼走廊末尾 203 号办公室盖章生效，可询问导诊台工作人员。
```

2022-07-03 03:25 UTC, septs commented on content/zh-cn/docs/psyco/midsouth/he-ying/index.md
> +1. 有意向建立和维持本地的跨性别社群，若就医者情绪稳定境况较好，会希望其能担任志愿者。
```suggestion
1. 本院仅对 **产前妇女** 提供 染色体核型分析 检查服务，但是 贺莹医生 可以介绍实验室进行检查。
1. 可前往 [龙智]({{ ref "xiangya3" }}) 医生处开具 HRT 处方。
1. 有意向建立和维持本地的跨性别社群，若就医者情绪稳定境况较好，会希望其能担任志愿者。
```

2022-07-04 17:15 UTC, ArtsEpiphany requested changes
感谢提交pr！有一处链接设置稍有问题需要修正，其他方面已经很不错啦。

有一个其实不是你造成的问题，就是「练肌肉」这行引用打断了编号，导致后续编号再次从1开始。如果你愿意的话可以顺便修复一下这个小问题。

2022-07-04 17:15 UTC, ArtsEpiphany commented on content/zh-cn/docs/psyco/midsouth/he-ying/index.md
> +1. 可前往 [龙智]({{ ref "xiangya3" }}) 医生处开具 HRT 处方。
```suggestion
1. 可前往 [龙智]({{< ref "xiangya3" >}}) 医生处开具 HRT 处方。
```
请注意，不符合格式的引用不会生效

2022-07-04 17:15 UTC, ArtsEpiphany commented on content/zh-cn/docs/psyco/midsouth/he-ying/index.md
> +1. 有意向建立和维持本地的跨性别社群，若就医者情绪稳定境况较好，会希望其能担任志愿者。
```suggestion
1. 贺莹医生有意向建立和维持本地的跨性别社群，若就医者情绪稳定境况较好，会希望其能担任志愿者。
```
缺主语

2022-07-05 02:37 UTC, ArtsEpiphany approved these changes

2022-07-05 02:38 UTC, merged