声明一些争议
mtf-wiki/MtF-Wiki pull request #532
Opened 2022-07-06 18:32 UTC by starsareintherose

2022-07-06 18:42 UTC, septs commented
建议重新编纂全文以便于保持全文逻辑顺畅

2022-07-09 13:57 UTC, saeziae requested changes

2022-07-09 13:57 UTC, saeziae commented on content/zh-cn/docs/campus/china/SDNU.md
> +体育课选修的话，男生往往只能选足球篮球之类的，有些老师比较松，上课和考试会容易一些。一般只要去上课就不会挂，但是对于 xyn 来说跑 1000 米可能比较吃亏（1000 米占 40%的期末成绩）。［似乎60%］
此处如不清楚，可以暂不写占比。

2022-07-09 13:57 UTC, saeziae commented on content/zh-cn/docs/campus/china/SDNU.md
> +大一和大二每学期都有步道乐跑，乐跑占体育期末成绩的 10%（然而有时候跑不完也未必扣分），每学期 15-30 次不等，男生要求 6-18 分钟内跑完 2km，可以骑自行车刷，但是最好不要用模拟定位刷，编者的 npy 曾经让编者用模拟定位刷结果险些封号。［生命科学学院不存在］
不存在什么？请写明

2022-07-09 13:57 UTC, saeziae commented on content/zh-cn/docs/campus/china/SDNU.md
> +同学素质有好有坏，npy 就是因为被男生舍友排挤而选择在外面租房子住。不过女生平均来说就会比较尊重和平常心对待，当小姐妹一样聊天之类的，总之就是感觉女生大多更能合得来。［女生内部矛盾也很多啊］
整段有主观性，可以删除。

2022-07-09 15:38 UTC, starsareintherose commented on content/zh-cn/docs/campus/china/SDNU.md
> +大一和大二每学期都有步道乐跑，乐跑占体育期末成绩的 10%（然而有时候跑不完也未必扣分），每学期 15-30 次不等，男生要求 6-18 分钟内跑完 2km，可以骑自行车刷，但是最好不要用模拟定位刷，编者的 npy 曾经让编者用模拟定位刷结果险些封号。［生命科学学院不存在］
她说的这一整段阿

2022-07-09 15:43 UTC, saeziae commented on content/zh-cn/docs/campus/china/SDNU.md
> +大一和大二每学期都有步道乐跑，乐跑占体育期末成绩的 10%（然而有时候跑不完也未必扣分），每学期 15-30 次不等，男生要求 6-18 分钟内跑完 2km，可以骑自行车刷，但是最好不要用模拟定位刷，编者的 npy 曾经让编者用模拟定位刷结果险些封号。［生命科学学院不存在］
不存在可以指没有校园跑任务，也可以指不存在假跑封号。

2022-07-09 16:49 UTC, starsareintherose commented
感觉整篇文章都像垃圾一样（

2022-07-09 16:49 UTC, closed without merging