Add Medroxyprogesterone acetate (MPA)
mtf-wiki/MtF-wiki pull request #715
Opened 2023-01-12 07:23 UTC by MlgmXyysd

1. 作为一种抗雄药品，醋酸甲羟孕酮（MPA）在圈内很少被提及，但常见的抗雄药物醋酸环丙孕酮（CPA）被禁止网售后很难在国内购买到，需要一种更易获取的抗雄方式，故添加此药品以供用药参考
2. 关于该药品的副作用及禁忌症需要更多资料及讨论
3. MPA 具有雄激素活性，可能会在一定程度减弱跨性别女性的女性化作用，目前普遍缺乏男性化作用的原因尚不明确
4. MPA 的大致作用原理为 抑制 HPA 和 HPG 轴，降低 LH 水平（LH 刺激性腺分泌性激素），导致体内性激素水平下降

references:
https://pubmed.ncbi.nlm.nih.gov/16286768/
Hormonal Sex Reassignment -> Male-to-Female Transsexuals https://en.wikipedia.org/wiki/Medroxyprogesterone_acetate Medical uses, Contraindications, Side effects, Pharmacology https://zh.wikipedia.org/wiki/%E5%A5%B3%E6%80%A7%E5%8C%96%E6%BF%80%E7%B4%A0%E7%96%97%E6%B3%95 药物 -> 跨性别女性药品和剂量
https://www.drugs.com/monograph/medroxyprogesterone.html Cautions for medroxyPROGESTERone
https://limelight.moe/t/topic/8298

Signed-off-by: Jaida Wu <mlgmxyysd@meowcat.org>

2023-01-12 08:15 UTC, MlgmXyysd commented
注：除 MPA 外，醋酸甲地孕酮（Megestrol acetate, MGA）也是有效的抗雄激素药物[^1][^2][^3][^4][^5][^6][^7]，通常被用于前列腺癌治疗[^8]、雄激素过多症[^9]、子宫内膜癌和晚期乳腺癌，但尚未查找到针对跨性别女性的相关研究，亦缺乏有效讨论[^10]

references:
[^1]: https://limelight.moe/t/topic/1713#h-15
治疗种类 -> 孕激素类 -> 抗促性腺激素和抗雄效果
[^2]: https://en.wikipedia.org/wiki/Feminizing_hormone_therapy
Medications -> Antiandrogens -> Steroidal antiandrogens
[^3]: https://en.wikipedia.org/wiki/Megestrol_acetate#Antigonadotropic_and_anticorticotropic_effects
Pharmacology -> Pharmacodynamics -> Antigonadotropic and anticorticotropic effects
[^4]: https://en.wikipedia.org/wiki/Megestrol_acetate#Androgenic_and_antiandrogenic_activity
Pharmacology -> Pharmacodynamics -> Androgenic and antiandrogenic activity
[^5]: https://pubmed.ncbi.nlm.nih.gov/6176985/
[^6]: https://pubmed.ncbi.nlm.nih.gov/8428326/
Steroidal Antiandrogens
[^7]: https://pubmed.ncbi.nlm.nih.gov/3930312/
[^8]: https://pubmed.ncbi.nlm.nih.gov/3552544/
[^9]: https://www.thieme-connect.de/products/ejournals/abstract/10.1055/s-2007-1021407
[^10]: https://www.reddit.com/r/asktransgender/comments/cpynwf/megestrol_acetate/

2023-01-12 09:46 UTC, Bersella-AI requested changes
关于剂量有一些建议：

1. 维基百科所指剂量范围过于宽泛，无法作为参考。
2. 根据 [Transfeminine Science 中文译本](https://tfsci.mtf.wiki/zh-cn/articles/cpa-dosage/#testosterone-suppression-in-combination-with-estrogen)所述，10 mg 醋酸甲羟孕酮相当于 1 mg 醋酸环丙孕酮（CPA）；但在此剂量下，睾酮水平仍降低 63%，接近于 5 mg 下 CPA 约七成的最大效力。（[引用来源](https://doi.org/10.1210/jc.2018-02253)）
3. 综上，10 ～ 20 mg 可能较合适。

此外，根据 [Transfeminine Science 中文译本](https://tfsci.mtf.wiki/zh-cn/articles/oral-p4-low-levels/#progestins-as-alternative-progestogens)与维基百科所述，MPA 仍有微弱雄激素效力和糖皮质激素效力，可能引起痤疮、体毛生长、脱发等雄激素敏感症状。需在其中特别注明这点。

2023-01-12 10:01 UTC, septs commented on content/zh-cn/docs/medicine/antiandrogen/medroxyprogesterone/index.md
> +| ![!](/images/medicine/medroxyprogesterone/xianju.jpg) | ![!](/images/medicine/medroxyprogesterone/silian.jpg) | ![!](/images/medicine/medroxyprogesterone/botaiweikang.jpg) | ![!](/images/medicine/m
可以使用 CSV 格式提高可维护性

2023-01-12 10:41 UTC, Bersella-AI approved these changes
差不多了，显示效果没问题、没有更多改动就吱一声。

2023-01-12 10:42 UTC, MlgmXyysd commented
ok

2023-01-12 11:16 UTC, septs commented on content/zh-cn/docs/medicine/antiandrogen/medroxyprogesterone/index.md
> +- 分子量：386.53
添加一个 CAS no

2023-01-12 11:56 UTC, MlgmXyysd commented on content/zh-cn/docs/medicine/antiandrogen/medroxyprogesterone/index.md
> +仙琚<sup>&reg;</sup>,浙江仙琚制药股份有限公司,2mg &times; 100 片/瓶,白色片,[国药准字 H33020715][H33020715],![!](/images/medicine/medroxyprogesterone/xianju.jpg)
草

2023-01-12 12:31 UTC, septs commented on content/zh-cn/docs/medicine/antiandrogen/medroxyprogesterone/index.md
> +- CAS RN：71-58-9
```suggestion
- CAS RN：[71-58-9](https://webbook.nist.gov/cgi/cbook.cgi?ID=71-58-9)
```

2023-01-14 17:45 UTC, septs approved these changes

2023-01-14 17:45 UTC, septs commented
由 @Bersella-AI 决定合并

2023-01-15 07:22 UTC, Bersella-AI approved these changes

2023-01-15 07:25 UTC, merged