Add: Androcur 10mg specs and pictures
mtf-wiki/MtF-wiki pull request #723
Opened 2023-01-23 11:39 UTC by LeeGuanLi

2023-01-25 09:11 UTC, Bersella-AI requested changes
此规格包装经辨识为德文，应为拜耳德国本部所产。尚未发现拜耳土耳其分公司是否有Androcur 10mg 产品的证据。本规格应归类为“德色”。

2023-01-25 09:51 UTC, LeeGuanLi commented
> 此规格包装经辨识为德文，应为拜耳德国本部所产。尚未发现拜耳土耳其分公司是否有Androcur 10mg 产品的证据。本规格应归类为"德色"。

@Bersella-AI 感谢提醒，此药生产公司为Jenapharm公司生产制造，系拜尔公司在德国的分公司

2023-01-25 10:33 UTC, Bersella-AI commented
查询发现还有一家德国药厂：Kohlpharma，也以 Bayer 品牌销售 Androcur 10 mg (https://www.shop-apotheke.com/arzneimittel/2474825/androcur-10.htm)。

2023-01-25 10:38 UTC, LeeGuanLi commented
> 查询发现还有一家德国药厂：Kohlpharma，也以 Bayer 品牌销售 Androcur 10 mg （ https://www.shop-apotheke.com/arzneimittel/2474825/androcur-10.htm ）。

因为这两家均为德国公司，我认为可以简称可以统称为德色，药企统称为拜尔（像pr里的那样）

2023-01-25 10:40 UTC, Bersella-AI commented
另有同样由 Kohlpharma 分销的 Androcur 50 mg （ https://www.shop-apotheke.com/arzneimittel/4954765/androcur.htm ），以及由 Jenapharm 分销的 Androcur 50 mg （ https://www.shop-apotheke.com/arzneimittel/3903317/androcur-50-mg.htm ）。因此，口服“德色”应有两种剂型，即 10 mg 与 50 mg。

2023-01-25 11:03 UTC, LeeGuanLi commented
> 另有同样由 Kohlpharma 分销的 Androcur 50 mg （ https://www.shop-apotheke.com/arzneimittel/4954765/androcur.htm ），以及由 Jenapharm 分销的 Androcur 50 mg （ https://www.shop-apotheke.com/arzneimittel/3903317/androcur-50-mg.htm ）。因此，口服“德色”应有两种剂型，即 10 mg 与 50 mg。

已提交更改，补充了50mg x 100片和50mg x 50片的规格和图片。

2023-01-25 12:59 UTC, Bersella-AI requested changes

2023-01-25 12:59 UTC, Bersella-AI commented on content/zh-cn/docs/medicine/antiandrogen/cyproterone/index.md
> +{{< figure src="/images/medicine/cyproterone/androcur-50x100.png" width="50%" >}}
既然此包装仅限于德国（德语区），干脆不做上市状态表格，改为两种规格（剂型）并列展示的表格。示例：

| 规格 | 10 mg | 50 mg |
|-|-|-|
| **包装示例** | （小图） | （小图） |
| **每盒定量** | 45 片 | 20、50、100 片 |
| **制造商** | 德国拜耳 | 德国拜耳 |
| **分销商（品牌）** | axicorp Pharma (Bayer)<br>Jenapharm<br>Kohlpharma (Bayer) | Jenapharm<br>Kohlpharma (Bayer) |

2023-01-25 13:36 UTC, LeeGuanLi commented on content/zh-cn/docs/medicine/antiandrogen/cyproterone/index.md
> +{{< figure src="/images/medicine/cyproterone/androcur-50x100.png" width="50%" >}}
此站点似乎不支持在csv元素中使用换行符分割内容，因此采用中文顿号对分销商名称进行区分。

包装因在正文中有提及，故没有放入表格。

2023-01-26 08:07 UTC, Bersella-AI commented on content/zh-cn/docs/medicine/antiandrogen/cyproterone/index.md
> +{{< figure src="/images/medicine/cyproterone/androcur-50x100.png" width="50%" >}}
其实可以用 `<br>` 换行。另一种换行符是 `\n` ，但不为 wiki 所支持。

2023-01-26 08:18 UTC, Bersella-AI requested changes

2023-01-26 08:18 UTC, Bersella-AI commented on content/zh-cn/docs/medicine/antiandrogen/cyproterone/index.md
> +- 规格：10mg &times; 45 片，50mg &times; 50 片，50mg &times; 100 片
这一段和上面表格有重复，稍显多余。对此仅需移除这段，在表格前写一句“由德国本土制造并销售的 Androcur，简称‘德色’“（仅供参考，可自由发挥），将两种规格的图片置入表格以便对比（酌情去掉一张 50 mg）。

2023-01-27 01:23 UTC, septs commented on content/zh-cn/docs/medicine/antiandrogen/cyproterone/index.md
> +- 规格：10mg &times; 45 片，50mg &times; 50 片，50mg &times; 100 片
更多规格的外包装图片并无实质意义？

2023-01-27 12:27 UTC, LeeGuanLi commented
已提交更改，注意查收。

2023-02-01 19:02 UTC, ArtsEpiphany reviewed
感谢提交pr！另外`androcur-50x50.png`这张图片似乎没有插入到页面中，如果认为无需插入这张图片的话，可以考虑删去此文件

2023-02-01 19:07 UTC, ArtsEpiphany commented
另外如果你比较繁忙的话，我们也可以先达成一致意见，然后我来帮你修改（看你似乎为这个pr花了不少精力）

2023-02-02 03:14 UTC, LeeGuanLi commented on content/zh-cn/docs/medicine/antiandrogen/cyproterone/index.md
> +- [说明书（德文）](/documents/D02579062-bp.pdf)
已将修改内容同步到pr

2023-02-03 06:55 UTC, Bersella-AI approved these changes
咱添了俩说明书翻译链接，没什么问题了现在。

2023-02-03 07:00 UTC, merged

2023-02-03 12:42 UTC, ArtsEpiphany commented on content/zh-cn/docs/medicine/antiandrogen/cyproterone/index.md
> +包装示例,{{< figure src="/images/medicine/cyproterone/androcur-10.png" width="20%" >}},{{< figure src="/images/medicine/cyproterone/androcur-50x100.png" width="20%" >}}
这个问题目前并没有解决，但Arts可以简单说一下造成这一点的原因。具体而言，`width="20%"`指定的是「图片的宽度是上一层结构宽度（即列宽）的20%」，而偏偏列宽的计算有依赖于该列所有格的宽度，因此会出现问题。（`width="100%"`的情况更容易想象，图片要求“我的宽度等于列宽”，列宽要求“我的宽度等于这一列最宽的元素宽度”，就出现了循环）