docs: thailand travel tips
mtf-wiki/MtF-wiki pull request #763
Opened 2023-03-09 05:03 UTC by Misaka-0x447f

2023-03-09 11:31 UTC, ArtsEpiphany reviewed
感谢提交pr！

2023-03-09 11:31 UTC, ArtsEpiphany commented on content/zh-cn/docs/srs/thailand/thailand-tips.md
> +- 每名游客只能携带一条烟（200支烟或250克烟草或50支雪茄），超出 10 倍罚款。
请注意这里的表述方式与其他条目不同。其他条目在直接列写违反法规的物品，而这一条是在介绍法律法规
```suggestion
- 每名游客只能携带一条烟（200 支烟或 250 克烟草或 50 支雪茄），超出 10 倍罚款。
```

2023-03-09 11:31 UTC, ArtsEpiphany commented on content/zh-cn/docs/srs/thailand/thailand-tips.md
> +- 成人物品。例如成人玩具、影像、书刊等。
性用品不是成年人的专属
```suggestion
- 与性有关的物品。例如性玩具、色情影像、色情书刊等。
```

2023-03-10 04:36 UTC, Misaka-0x447f commented on content/zh-cn/docs/srs/thailand/thailand-tips.md
> +- 成人物品。例如成人玩具、影像、书刊等。
fixed

2023-03-10 04:37 UTC, Misaka-0x447f commented on content/zh-cn/docs/srs/thailand/thailand-tips.md
> +- 每名游客只能携带一条烟（200支烟或250克烟草或50支雪茄），超出 10 倍罚款。
fixed

2023-03-10 06:43 UTC, ArtsEpiphany approved these changes
辛苦了qwq

2023-03-10 11:40 UTC, saeziae requested changes
建议将内容挪后，不要放在物品材料准备等必要内容前面

2023-03-10 15:00 UTC, septs commented on content/zh-cn/docs/srs/thailand/thailand-tips.md
> +  - 任何大象的身体组成部分，包括精液、胚胎、汗毛、肉、皮、牙、指甲、骨头、血液、脱氧核糖核酸（DNA）以及相关制成品均属违法。
"脱氧核糖核酸（DNA）" 这个说法有点怪（指相对前面的内容）

2023-03-12 09:48 UTC, Misaka-0x447f commented on content/zh-cn/docs/srs/thailand/thailand-tips.md
> +  - 任何大象的身体组成部分，包括精液、胚胎、汗毛、肉、皮、牙、指甲、骨头、血液、脱氧核糖核酸（DNA）以及相关制成品均属违法。
fixed

2023-03-12 09:49 UTC, Misaka-0x447f commented
建议尽快合并，成人玩具这个太多人都不知道

2023-03-12 10:01 UTC, septs commented on content/zh-cn/docs/srs/thailand/thailand-tips.md
> +  - 可以通过 Airalo app 购买 esim 卡。
```suggestion
  - 可以通过 [Airalo](https://www.airalo.com) 购买 eSIM 卡。
```

2023-03-12 10:02 UTC, Misaka-0x447f commented
建议尽快合并

2023-03-12 18:10 UTC, merged