Update index.md
mtf-wiki/MtF-Wiki pull request #839
Opened 2023-08-01 17:41 UTC by daanser

2023-08-01 23:41 UTC, Cryolitia requested changes

2023-08-01 23:41 UTC, Cryolitia commented on content/zh-cn/docs/psyco/beijing/hu-peicheng/index.md
> +- 有案例显示胡佩诚不少于两次对**持病历未成年跨儿拒绝开证**并表示回龙观病历无法在北医三院获得任何激素治疗。但实际未成年持回龙观病历(至少)可在北医三院内分泌科获得gnrha。
```suggestion
- 有案例显示胡佩诚不少于两次对**持病历未成年跨儿拒绝开证**并表示回龙观病历无法在北医三院获得任何激素治疗。但实际未成年持回龙观病历(至少)可在北医三院内分泌科获得 GnRHa。
```

2023-08-02 13:20 UTC, daanser commented
不太会用github，我还要操作什么吗

2023-08-02 13:21 UTC, Cryolitia approved these changes

2023-08-02 13:21 UTC, merged