Update thailand-tips.md
mtf-wiki/MtF-Wiki pull request #984
Opened 2024-03-12 03:42 UTC by Ethanlita

更新了入境有关信息和部分行前准备信息

2024-03-12 03:45 UTC, Cryolitia commented on content/zh-cn/docs/srs/thailand/thailand-tips.md
> +  - 如果是平时使用针剂的女孩子，请提前预约手术结束后去哪里打针。
可能需要补充关于泰国使用注射剂型的更多信息

2024-03-12 03:52 UTC, Ethanlita commented on content/zh-cn/docs/srs/thailand/thailand-tips.md
> +  - 如果是平时使用针剂的女孩子，请提前预约手术结束后去哪里打针。
这个我还真补充不了，只能说Phyathai2医院的医生会考虑这个问题，他们给我使用的是和我在日本使用的规格是一致的

2024-03-12 04:07 UTC, Cryolitia commented on content/zh-cn/docs/srs/thailand/thailand-tips.md
> +  - 如果是平时使用针剂的女孩子，请提前预约手术结束后去哪里打针。
可以提供注射的地点/需要的材料/etc……

就这么说一句提前预约大家也不知道去哪里预约怎么预约啊，不能提供更多消息的话就让大家在泰国期间用凝胶或者诺坤复吧

2024-03-12 05:41 UTC, Ethanlita commented on content/zh-cn/docs/srs/thailand/thailand-tips.md
> +  - 如果是平时使用针剂的女孩子，请提前预约手术结束后去哪里打针。
确实，但是这样子并不安全，因为你不能简单换算，例如每两周进行1A的雌二醇注射的人，她们应该考虑使用多少凝胶呢？胡乱使用是有安全问题的。因此，即使不能提供很多信息，无论如何至少应该提到这件事情，让有这块需求的女孩子明白她们可以有这个选择
至于怎么预约，一般思路就是联系自己的医院和诊所解决这个问题，我只知道PAI可以帮助预约，至于其他的医院和诊所，我的建议是等别人来补充信息

2024-03-12 06:28 UTC, Cryolitia commented on content/zh-cn/docs/srs/thailand/thailand-tips.md
> +  - 如果是平时使用针剂的女孩子，请提前预约手术结束后去哪里打针。
使用凝胶当然是按医嘱和说明书的剂量使用，和此前用不用针剂关系不大

很显然针剂并没有普及到可以默认每个去泰国的人都知道怎么找到且可以找到，如果这在所有提供手术的诊所都是常态的话就直接写可以先诊所咨询，不然就应详细写出哪些诊所为自己的手术病人提供这类服务，哪些HRT专科提供此类服务，具体应该如何获得。

若无法写出这些信息，不建议增加此行。

2024-03-12 07:28 UTC, Ethanlita commented on content/zh-cn/docs/srs/thailand/thailand-tips.md
> +  - 如果是平时使用针剂的女孩子，请提前预约手术结束后去哪里打针。
进行了调查并增加了数据，应该足以覆盖大部分情况了

2024-03-14 08:22 UTC, Cryolitia commented on content/zh-cn/docs/srs/thailand/thailand-tips.md
> +对于服用药物或使用凝胶的女孩子，可以从国内携带，或者在泰国购买，非常方便。
```suggestion
## 如果你手术后需要恢复使用性激素

对于服用药物或使用凝胶的女孩子，可以从国内携带，或者在泰国购买，非常方便。
```

2024-03-14 08:25 UTC, Cryolitia reviewed
女孩子建议改为女性倾向跨性别者，不过这样口语化一点也没有过于不妥。不对此条给出阻止合并意见。

等待泰国手术维护组review

2024-03-14 08:25 UTC, Cryolitia commented on content/zh-cn/docs/srs/thailand/thailand-tips.md
> +- 准备泰铢现金，泰国是现金社会。
似乎有些地方不接受现金纸钞，泰国法律亦没有强制要求接受纸钞

2024-03-29 23:14 UTC, clansty requested changes

2024-03-29 23:14 UTC, clansty commented on content/zh-cn/docs/srs/thailand/thailand-tips.md
> +- TrueMove、dtac 等泰国运营商电话卡，可以于国内、泰国机场、泰国 711 购买，可在 711 或者营业厅等地充值余额。可以通过 [Airalo](https://www.airalo.com) 购买 eSIM 卡。目前dtac和AIS提供中文的网上营业厅，网上充话费可以使用支付宝和信用卡付费。此外，dtac提供中文客服。
```suggestion
- TrueMove、dtac 等泰国运营商电话卡，可以于国内、泰国机场、泰国 711 购买，可在 711 或者营业厅等地充值余额。可以通过 [Airalo](https://www.airalo.com) 购买 eSIM 卡。目前 dtac 和 AIS 提供中文的网上营业厅，网上充话费可以使用支付宝和信用卡付费。此外，dtac 提供中文客服。
```

2024-03-29 23:14 UTC, clansty commented on content/zh-cn/docs/srs/thailand/thailand-tips.md
> +- Suporn Clinic要求提供公证翻译件，需要且必须要一份证明，之后由泰国的心理医生开具第二份证明。
```suggestion
- Suporn Clinic 要求提供公证翻译件，需要且必须要一份证明，之后由泰国的心理医生开具第二份证明。
```

2024-03-29 23:14 UTC, clansty commented on content/zh-cn/docs/srs/thailand/thailand-tips.md
> +- PAI直接会预约两位泰国的精神科医生；
```suggestion
- PAI 直接会预约两位泰国的精神科医生；
```

2024-03-29 23:14 UTC, clansty commented on content/zh-cn/docs/srs/thailand/thailand-tips.md
> +- Kamol医院内部有心理医生，可以直接开具证明，费用已经包含。
```suggestion
- Kamol 医院内部有心理医生，可以直接开具证明，费用已经包含。
```

2024-03-29 23:14 UTC, clansty commented on content/zh-cn/docs/srs/thailand/thailand-tips.md
> +- 在PAI进行手术的女孩子，PAI诊所工作人员或者Charee可以帮忙预约Phyathai 2医院的妇科医生开单注射，费用为1860泰铢。
```suggestion
- 在PAI进行手术的女孩子，PAI 诊所工作人员或者 Charee 可以帮忙预约 Phyathai 2 医院的妇科医生开单注射，费用为 1860 泰铢。
```

2024-03-29 23:14 UTC, clansty commented on content/zh-cn/docs/srs/thailand/thailand-tips.md
> +- 在Kamol Hospital进行手术的女孩子，医院的工作人员可以帮助预约其他医院的妇科医生开具处方。（暂不确定是哪个医院）
```suggestion
- 在 Kamol Hospital 进行手术的女孩子，医院的工作人员可以帮助预约其他医院的妇科医生开具处方。（暂不确定是哪个医院）
```

2024-03-29 23:14 UTC, clansty commented on content/zh-cn/docs/srs/thailand/thailand-tips.md
> +- 在Suporn Clinic进行手术的女孩子，复诊时诊所经理（Suporn医生的妻子）可以帮忙联系Samitivej医院。
```suggestion
- 在 Suporn Clinic 进行手术的女孩子，复诊时诊所经理（Suporn 医生的妻子）可以帮忙联系 Samitivej 医院。
```

2024-03-29 23:14 UTC, clansty commented on content/zh-cn/docs/srs/thailand/thailand-tips.md
> +- 在水门诊所进行手术的女孩子，由于诊所不提供任何协助，可以自行联系Phyathai 2医院的国际部门，预约Unnop Jaisamrarn医生。预约方法参见<https://phyathai2international.com/en/make-an-appointment>，Phyathai 2医院是国际医院，提供中文翻译服务。（如果遇上诊所不提供HRT的情况也可以使用此方法联系Phyatha
```suggestion
- 在水门诊所进行手术的女孩子，由于诊所不提供任何协助，可以自行联系 Phyathai 2 医院的国际部门，预约 Unnop Jaisamrarn 医生。预约方法参见<https://phyathai2international.com/en/make-an-appointment>，Phyathai 2 医院是国际医院，提供中文翻译服务。（如果遇上诊所不提供HRT的情况也可以使用此方法联系 Phyathai 2 医院。）
```

2024-03-29 23:20 UTC, clansty commented on content/zh-cn/docs/srs/thailand/thailand-tips.md
> +  - 如果是平时使用针剂的女孩子，请提前预约手术结束后去哪里打针。
```suggestion
  - 如果你平时使用针剂，请提前预约手术结束后去哪里打针。
```

建议改为性别中性一点的语气。去泰国手术的并不一定只有女孩子，ta 的性别认同可能是非二元或者其他的

下同

2024-04-06 02:26 UTC, Cryolitia commented
作者超过两周未回复，考虑在此PR上直接执行修改后合并。 CC @clansty

2024-04-06 02:55 UTC, clansty requested changes

2024-04-06 02:55 UTC, clansty commented on content/zh-cn/docs/srs/thailand/thailand-tips.md
> +- 在水门诊所进行手术的女孩子，由于诊所不提供任何协助，可以自行联系 Phyathai 2 医院的国际部门，预约 Unnop Jaisamrarn 医生。预约方法参见<https://phyathai2international.com/en/make-an-appointment>，Phyathai 2 医院是国际医院，提供中文翻译服务。（如果遇上诊所不提供HRT的情况也可以使用此方法联系 P
```suggestion
如果你服用药物或使用凝胶，可以从国内携带，或者在泰国购买，非常方便。
如果你对于在医院进行针剂注射，可以带上病历证明等，以及你的药品的照片，联系你的诊所：
- 如果你在 PAI 进行手术，PAI 诊所工作人员或者 Charee 可以帮忙预约 Phyathai 2 医院的妇科医生开单注射，费用为 1860 泰铢。
- 如果你在 Kamol Hospital 进行手术，医院的工作人员可以帮助预约其他医院的妇科医生开具处方。（暂不确定是哪个医院）
- 如果你在 Suporn Clinic 进行手术，复诊时诊所经理（Suporn 医生的妻子）可以帮忙联系 Samitivej 医院。
- 如果你在水门诊所进行手术，由于诊所不提供任何协助，可以自行联系 Phyathai 2 医院的国际部门，预约 Unnop Jaisamrarn 医生。预约方法参见 <https://phyathai2international.com/en/make-an-appointment>，Phyathai 2 医院是国际医院，提供中文翻译服务。（如果遇上诊所不提供HRT的情况也可以使用此方法联系 Phyathai 2 医院。）
```

2024-04-06 02:55 UTC, clansty commented on content/zh-cn/docs/srs/thailand/thailand-tips.md
> +当前泰国对中国普通护照持有人实行免签证，普通护照持有人可以免签证入境30天，入境后可以缴纳延期费用后延长30天（或转换成其他签证），基本上已经足够应付术后恢复不好等情况。
```suggestion
当前泰国对中国普通护照持有人实行免签证，普通护照持有人可以免签证入境 30 天，入境后可以缴纳延期费用后延长30天（或转换成其他签证），基本上已经足够应付术后恢复不好等情况。
```

2024-04-06 02:56 UTC, clansty approved these changes

2024-04-06 02:58 UTC, CoelacanthusHex approved these changes

2024-04-06 03:00 UTC, clansty commented on content/zh-cn/docs/srs/thailand/thailand-tips.md
> +- 准备泰铢现金，泰国是现金社会。
这个我单独写一下吧

2024-04-06 03:00 UTC, merged